<a href="https://colab.research.google.com/github/Tharindu8654/Python/blob/main/setosa_versicolor_virginica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
from sklearn.datasets import load_iris
iri_datasets = load_iris()
print("Keys of iris_datasets : \n", iri_datasets.keys())

Keys of iris_datasets : 
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [12]:
print(iri_datasets['DESCR'][:193]+"\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive 
...


In [13]:
print("Target names : \n", iri_datasets['target_names'])

Target names : 
 ['setosa' 'versicolor' 'virginica']


In [15]:
print("Fearture names : \n", iri_datasets['feature_names'])

Fearture names : 
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [17]:
print("Type of data : \n",type(iri_datasets['data']))

Type of data : 
 <class 'numpy.ndarray'>


In [20]:
print("Shape of data sets :\n ",iri_datasets['data'].shape)

Shape of data sets :
  (150, 4)


In [22]:
print("First five smaple Datasets :\n",iri_datasets['data'][:5])

First five smaple Datasets :
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [23]:
print("Type of Target : \n", type(iri_datasets['target']))

Type of Target : 
 <class 'numpy.ndarray'>


In [25]:
print("shape OF Target \n:",iri_datasets['target'].shape)

shape OF Target 
: (150,)


In [26]:
print("Target :\n",iri_datasets['target'])

Target :
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [30]:
from sklearn.model_selesction import train_test_split
X_train,X-test,y_train, y_test = train_test_split(iri_datasets['data'],iri_datasets['target'],random_state =23)

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train, y_test = train_test_split(iri_datasets['data'],iri_datasets['target'],random_state =23)

In [32]:
print("X - train shape : \n",X_train.shape)

X - train shape : 
 (112, 4)


In [33]:
print("X - test shape : \n",X_test.shape)

X - test shape : 
 (38, 4)


In [34]:
print("Y training data :\n", y_train.shape)

Y training data :
 (112,)


In [35]:
print("Y testing data : \n", y_test.shape)

Y testing data : 
 (38,)


In [38]:
import pandas as pd

pd.plotting.scatter_matrix(pd.DataFrame(X_train, columns = iri_datasets.feature_names), c = y_train, figsize = (15,15), marker = 'o', hist_kwds = {'bins':20}, s = 60, alpha = .8)

array([[<Axes: xlabel='sepal length (cm)', ylabel='sepal length (cm)'>,
        <Axes: xlabel='sepal width (cm)', ylabel='sepal length (cm)'>,
        <Axes: xlabel='petal length (cm)', ylabel='sepal length (cm)'>,
        <Axes: xlabel='petal width (cm)', ylabel='sepal length (cm)'>],
       [<Axes: xlabel='sepal length (cm)', ylabel='sepal width (cm)'>,
        <Axes: xlabel='sepal width (cm)', ylabel='sepal width (cm)'>,
        <Axes: xlabel='petal length (cm)', ylabel='sepal width (cm)'>,
        <Axes: xlabel='petal width (cm)', ylabel='sepal width (cm)'>],
       [<Axes: xlabel='sepal length (cm)', ylabel='petal length (cm)'>,
        <Axes: xlabel='sepal width (cm)', ylabel='petal length (cm)'>,
        <Axes: xlabel='petal length (cm)', ylabel='petal length (cm)'>,
        <Axes: xlabel='petal width (cm)', ylabel='petal length (cm)'>],
       [<Axes: xlabel='sepal length (cm)', ylabel='petal width (cm)'>,
        <Axes: xlabel='sepal width (cm)', ylabel='petal width (cm)'>,
  

In [39]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)

In [40]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [41]:
import numpy as np
X_new =np.array([[5,2.9,1,0.2]])
print("X new Shape: \n",X_new.shape)

X new Shape: 
 (1, 4)


In [42]:
prediction = knn.predict(X_new)
print("Prediction :\n", prediction)
print("pPredicted target name:\n ", iri_datasets['target_names'][prediction])

Prediction :
 [0]
pPredicted target name:
  ['setosa']


In [44]:
y_pred = knn.predict(X_test)
print("Test set predictions :\n", y_pred)

Test set predictions :
 [2 2 1 0 2 1 0 2 0 1 1 0 2 0 0 1 1 1 2 0 2 0 0 0 2 0 0 2 1 1 0 1 0 2 0 0 1
 1]


In [47]:
from sklearn.metrics import accuracy_score
#print("Test set Score :{:.2f}".format(np.mean(y_pred ==y_test)))
print(accuracy_score(y_test, y_pred))

0.9736842105263158
